# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBear < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bear"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.8.0/care-bear_0.8.0_darwin_amd64.tar.gz"
      sha256 "f805ef1f03fbbff44e8d98fc0b9da9d6e6f27f60e1e675f8a49fcfac29660674"

      define_method(:install) do
        bin.install "care-bear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.8.0/care-bear_0.8.0_darwin_arm64.tar.gz"
      sha256 "cdb2bc5b8c36fd666fb579f45c66d7de0de574dac35e898088d11731b56f970a"

      define_method(:install) do
        bin.install "care-bear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.8.0/care-bear_0.8.0_linux_amd64.tar.gz"
      sha256 "7f2570538cf057f7da0aa8b976098c8498afb2fb8f24e5fb53610a7fdbad4c29"
      define_method(:install) do
        bin.install "care-bear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.8.0/care-bear_0.8.0_linux_arm64.tar.gz"
      sha256 "dc9f51fe2a1b7d85478d4c94b935c6780e8f50d3fd9c3cb19592b528cf624b8a"
      define_method(:install) do
        bin.install "care-bear"
      end
    end
  end

  test do
    system "#{bin}/care-bear", "version"
  end
end
