# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBear < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bear"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.0/care-bear_0.5.0_darwin_amd64.tar.gz"
      sha256 "f0f5d6d2fbca01272bcdc0461e9a616c41ed430360b3ec607cdfa31a06ecea32"

      define_method(:install) do
        bin.install "care-bear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.0/care-bear_0.5.0_darwin_arm64.tar.gz"
      sha256 "56a9fe0b5536c95e38624bb0e58ab2181bbd0f93936c22ff77836b28c832381a"

      define_method(:install) do
        bin.install "care-bear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.0/care-bear_0.5.0_linux_amd64.tar.gz"
      sha256 "dc579c807bae7506cf02ce1acd229b7589a5c0b7a23fce98e08a75ee608f6975"
      define_method(:install) do
        bin.install "care-bear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.0/care-bear_0.5.0_linux_arm64.tar.gz"
      sha256 "99484f82cc08a8d37325cde249fa38db58255cef70190ff3937d4e772ce46ea8"
      define_method(:install) do
        bin.install "care-bear"
      end
    end
  end

  test do
    system "#{bin}/care-bear", "version"
  end
end
