# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBare < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bare"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.4.0/care-bare_0.4.0_darwin_amd64.tar.gz"
      sha256 "12c907b7a7498850646dfc26330ebe2fe92613a2fe7c420efb71343997d1203a"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.4.0/care-bare_0.4.0_darwin_arm64.tar.gz"
      sha256 "c6a92ede6dbc3b969ddd5680fd278b8fee99502aba0e4af332168a2dacf9feb8"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.4.0/care-bare_0.4.0_linux_amd64.tar.gz"
      sha256 "e047ae9eafc8e4a93c20e548d14acbdb45afcb00ec90ce63c5a434b695045078"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.4.0/care-bare_0.4.0_linux_arm64.tar.gz"
      sha256 "735e7f78d99e5e3af9599f1c2adc096a66faab193b571c8589a93b0446573f24"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  test do
    system "#{bin}/care-bare", "version"
  end
end
