# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBear < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bear"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.1/care-bear_0.5.1_darwin_amd64.tar.gz"
      sha256 "b334aff7642bc5dffe2ec09eb15ba5a2f1695231f017e9a71cc100ba784171ce"

      define_method(:install) do
        bin.install "care-bear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.1/care-bear_0.5.1_darwin_arm64.tar.gz"
      sha256 "879fd69885b0f3350c9e4ee9df782098113273f1dac7c4e9aa1e98b5ea28164d"

      define_method(:install) do
        bin.install "care-bear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.1/care-bear_0.5.1_linux_amd64.tar.gz"
      sha256 "cddc89c79837e456a55545b384154be235317f0dfd247a69a30abf3553535c89"
      define_method(:install) do
        bin.install "care-bear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bear/releases/download/v0.5.1/care-bear_0.5.1_linux_arm64.tar.gz"
      sha256 "de475961dfd70bc0731db66e597391edd77d9c1a359429dca9196d119cb7a804"
      define_method(:install) do
        bin.install "care-bear"
      end
    end
  end

  test do
    system "#{bin}/care-bear", "version"
  end
end
