# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBare < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bare"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.3.0/care-bare_0.3.0_darwin_amd64.tar.gz"
      sha256 "1aa1bb5b7fc9381983a82dfc4a6ea8c681c4052a479c919f94d674d2f188abd1"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.3.0/care-bare_0.3.0_darwin_arm64.tar.gz"
      sha256 "418eecee879abdc2acfaa60e53b2811a064c72c77c545fc0c43cd2aa3a91616b"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.3.0/care-bare_0.3.0_linux_amd64.tar.gz"
      sha256 "bf2636e82805ad1a762a70efc815af633be5c90af35f091f2906a42175a35bf0"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.3.0/care-bare_0.3.0_linux_arm64.tar.gz"
      sha256 "fa2e49caa5c260e9068d6a1eafa4d345a756dac2c30df2df1d7030bc2c756714"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  test do
    system "#{bin}/care-bare", "version"
  end
end
